[project]
name = "dedalus-marimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dedalus>=3.0.4",
    "marimo>=0.18.4",
]
